### PR TITLE
Fix #23 - Replace only some java.lang classes and support subtypes

### LINKED ISSUE #23: Java demangler gives broken results for some classes in Java APIs
As described in rizinorg/rizin#2648, the Java demangler tries to remove any "java/lang/" strings from a mangled class/method/field (on line 274 of [java.c](https://github.com/rizinorg/rz-libdemangle/blob/main/src/java.c)).

It's a nice feature that simplifies the demangled result for classes in the [java.lang](https://docs.oracle.com/javase/7/docs/api/java/lang/package-summary.html) package. However, it also breaks those with package names starting with "java.lang", such as classes in [java.lang.annotation](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/package-summary.html), [java.lang.reflect](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/package-summary.html), [java.lang.invoke](https://docs.oracle.com/javase/7/docs/api/java/lang/invoke/package-summary.html), etc.

For example, in the following screenshot, the demangler takes the method, `getMethod(Ljava/lang/Class;)Ljava/lang/reflect/Method;`, as the input and returns `reflect.Method getMethod(Class)`. The result shows that the return type is `reflect.Method`. But according to the input, it should be `java.lang.reflect.Method`.

### Expected behavior

The Java demangler performs more checks to avoid only removing parts of the package name.

### Actual behavior

The Java demangler removes all the "java/lang" strings from the input. Thus, it generates broken demangled results for some classes in Java APIs.

### Steps to reproduce the behavior

- Please open [this sample](https://github.com/quark-engine/apk-malware-samples/raw/master/Ahmyth.apk) with the latest Rizin.
- Run the following commands.

```
aaa
is~2768
```

Also, please feel free to let me know if I've missed something. I can work on the PR if this is indeed an issue.

### PR DESCRIPTION
**Pull request by wargio**
Replaces only some `java.lang` classes (like Void, String, etc..) and adds support for subtypes (including templates)

Fix #23 

@haeter525 Please verify this PR.

### CODE REVIEW

File: src/java.c [hunk 1]
```diff
@@ -3,13 +3,56 @@
...
+	const char *search;
+	const char *replace;
+} java_replace_t;
+
 #define is_native_type(x) ((x) && !IS_UPPER(x))
 #define is_varargs(x)     ((x)[0] == '.' && (x)[1] == '.' && (x)[2] == '.')
 
-static inline bool demangle_type(char *type, DemString *sb, size_t *used) {
-	bool array = false, varargs = false;
+static java_replace_t java_replace_table[] = {
```
Comment (XVilka) [inline src/java.c:14]: Please add a comment where from and what for this table is

**Review by XVilka — CHANGES_REQUESTED** [review]
LGTM.

**Comment by haeter525** [comment]
> @haeter525 Please verify this PR.

Confirm #23 is fixed. Thanks :D

**Review by XVilka — APPROVED** [review]
