### PR TITLE
Added more tests and fixed issues demangling when suffix _ptr/_<num> are present

### LINKED ISSUE #9: Failure to demangle some C++ functions
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 33 x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/31a2406f461d8f15c5789b855e7eaa9cb4dc120e

### Expected behavior

Functions demangled successfully

### Actual behavior

image

### Steps to reproduce the behavior

```
                                       
[0x0007aca0]> afl~sym._ZN
0x0018a870   63 1271 -> 1240 sym._ZNSt10_HashtableI21BNLowLevelILOperationSt4pairIKS0_St6vectorIN11BinaryNinja22LowLevelILOperandUsageESaIS5_EEESaIS8_ENSt8__d
0x00167170   18 463  -> 413  sym._ZNSt8__detail9_Map_baseI22BNHighLevelILOperationSt4pairIKS1_St13unordered_mapIN11BinaryNinja23HighLevelILOperandUsageEmSt4ha
0x0018b090   17 304  -> 292  sym._ZNSt10_HashtableIN11BinaryNinja22LowLevelILOperandUsageESt4pairIKS1_mESaIS4_ENSt8__detail10_Select1stESt8equal_toIS1_ESt4has
0x001675b0   10 229  -> 227  sym._ZNSt10_HashtableIN11BinaryNinja23HighLevelILOperandUsageESt4pairIKS1_NS0_22HighLevelILOperandTypeEESaIS5_ENSt8__detail10_Sel
0x00188690   13 238  -> 233  sym._ZNSt10_HashtableI21BNLowLevelILOperationSt4pairIKS0_St13unordered_mapIN11BinaryNinja22LowLevelILOperandUsageEmSt4hashIS5_ESt
0x00166780   63 1271 -> 1240 sym._ZNSt10_HashtableI22BNHighLevelILOperationSt4pairIKS0_St6vectorIN11BinaryNinja23HighLevelILOperandUsageESaIS5_EEESaIS8_ENSt8
0x00163cf0   13 238  -> 233  sym._ZNSt10_HashtableI22BNHighLevelILOperationSt4pairIKS0_St13unordered_mapIN11BinaryNinja23HighLevelILOperandUsageEmSt4hashIS5_E
0x001a1e10   13 238  -> 233  sym._ZNSt10_HashtableI24BNMediumLevelILOperationSt4pairIKS0_St13unordered_mapIN11BinaryNinja25MediumLevelILOperandUsageEmSt4hashI
0x001a2c80   63 1271 -> 1240 sym._ZNSt10_HashtableI24BNMediumLevelILOperationSt4pairIKS0_St6vectorIN11BinaryNinja25MediumLevelILOperandUsageESaIS5_EEESaIS8_EN
0x0018b2f0   10 229  -> 227  sym._ZNSt10_HashtableIN11BinaryNinja22LowLevelILOperandUsageESt4pairIKS1_NS0_21LowLevelILOperandTypeEESaIS5_ENSt8__detail10_Selec
0x0018f5a0   10 229  -> 223  sym._ZNSt10_HashtableImSt4pairIKm20BNILBranchDependenceESaIS3_ENSt8__detail10_Select1stESt8equal_toImESt4hashImENS5_18_Mod_range
0x00167350   17 304  -> 292  sym._ZNSt10_HashtableIN11BinaryNinja23HighLevelILOperandUsageESt4pairIKS1_mESaIS4_ENSt8__detail10_Select1stESt8equal_toIS1_ESt4ha
0x001a1f00    6 119  -> 110  sym._ZNSt10_HashtableIN11BinaryNinja25MediumLevelILOperandUsageESt4pairIKS1_mESaIS4_ENSt8__detail10_Select1stESt8equal_toIS1_ESt4
0x0018aeb0   18 463  -> 413  sym._ZNSt8__detail9_Map_baseI21BNLowLevelILOperationSt4pairIKS1_St13unordered_mapIN11BinaryNinja22LowLevelILOperandUsageEmSt4hash
0x001a35d0   17 304  -> 292  sym._ZNSt10_HashtableIN11BinaryNinja25MediumLevelILOperandUsageESt4pairIKS1_NS0_24MediumLevelILOperandTypeEESaIS5_ENSt8__detail10
0x001a32c0   18 463  -> 413  sym._ZNSt8__detail9_Map_baseI24BNMediumLevelILOperationSt4pairIKS1_St13unordered_mapIN11BinaryNinja25MediumLevelILOperandUsageEmS
```

After opening `binaryninja` executable in IDA Pro 7.5 SP3, I exported the demangled functions into a MAP file. 
[binaryninja.map.zip](https://github.com/rizinorg/rizin/files/6161250/binaryninja.map.zip)

### PR DESCRIPTION
**Pull request by wargio**
Resolves the issue when demangling strings ending in `_ptr` or `_<num>` (even when multiple nums are found.

Fix #9

### CODE REVIEW

File: src/cxx.c [hunk 1]
```diff
@@ -42,6 +42,39 @@ char *libdemangle_handler_cxx(const char *str) {
 			*glibcxx = '\0';
 		}
 	}
+
+	uint32_t len = strlen(p);
+	if (len > 4 && !strncmp(p + len - 4, "_ptr", 4)) {
```
Comment (XVilka) [inline src/cxx.c:47]: What about converting 4 to strlen("_ptr") there?

Comment (wargio) [reply src/cxx.c:47]: doesn't change much the code.

**Review by XVilka — APPROVED** [review]
Good job! I can confirm it fixes the problem.
